// Generated by scripts/extract-compat.ts — do not edit by hand.
// Regenerate with: bun run scripts/extract-compat.ts
// Support data © caniuse-lite contributors, CC-BY-4.0 — https://github.com/browserslist/caniuse-lite
// Rows with source "curated" are not in caniuse-lite; their support tables follow
// documented Chromium/Safari release versions.

export const COMPAT_DATA_SOURCE = {
  "package": "caniuse-lite",
  "version": "1.0.30001810",
  "generatedAt": "2026-09-20",
  "license": "CC-BY-4.0",
  "url": "https://github.com/browserslist/caniuse-lite"
} as const;

export type SupportLevel = "yes" | "partial" | "no" | "unknown";
export type ProfileKey = "android66" | "android96" | "ios12" | "ios13";

export interface DeviceProfile {
  key: ProfileKey;
  label: string;
  era: string;
  browsers: { browser: string; version: string }[];
}

export const PROFILES: DeviceProfile[] = [
  {
    "key": "android66",
    "label": "Android WebView 66",
    "era": "Android 9-era low-end devices (Chromium 66)",
    "browsers": [
      {
        "browser": "chrome",
        "version": "66"
      },
      {
        "browser": "samsung",
        "version": "8.2"
      }
    ]
  },
  {
    "key": "android96",
    "label": "Android WebView 96",
    "era": "Android 11-era mid-range devices (Chromium 96)",
    "browsers": [
      {
        "browser": "chrome",
        "version": "96"
      },
      {
        "browser": "samsung",
        "version": "12.0"
      }
    ]
  },
  {
    "key": "ios12",
    "label": "iOS Safari 12",
    "era": "iPhone 6/5s-era devices that stopped at iOS 12",
    "browsers": [
      {
        "browser": "ios_saf",
        "version": "12.4"
      }
    ]
  },
  {
    "key": "ios13",
    "label": "iOS Safari 13",
    "era": "A9/A10 iPhones that stopped at iOS 13",
    "browsers": [
      {
        "browser": "ios_saf",
        "version": "13.6"
      }
    ]
  }
];

export interface CompatFeature {
  id: string;
  label: string;
  category: "js" | "css";
  /** Regex sources; a single hit marks the feature as shipped by the site. */
  tokens: string[];
  /** 1–3; higher weight = likelier to break rendering or interaction. */
  weight: number;
  support: Record<ProfileKey, SupportLevel>;
  source: "caniuse" | "curated";
  fix: string;
}

export const FEATURES: CompatFeature[] = [
  {
    "id": "optional-chaining",
    "label": "Optional chaining (`?.`)",
    "category": "js",
    "tokens": [
      "\\?\\.[\\w(]"
    ],
    "weight": 3,
    "source": "curated",
    "fix": "Lower the TypeScript/Babel target below Chrome 80 (e.g. browserslist `chrome 66`) so `?.` compiles away, or add the official transform.",
    "support": {
      "android66": "no",
      "android96": "yes",
      "ios12": "no",
      "ios13": "yes"
    }
  },
  {
    "id": "nullish-coalescing",
    "label": "Nullish coalescing (`??`)",
    "category": "js",
    "tokens": [
      "\\?\\?(?!=)"
    ],
    "weight": 3,
    "source": "curated",
    "fix": "Compile `??` for legacy targets (Babel nullish-coalescing transform) or replace with explicit `=== null || === undefined` checks.",
    "support": {
      "android66": "no",
      "android96": "yes",
      "ios12": "no",
      "ios13": "yes"
    }
  },
  {
    "id": "logical-assignment",
    "label": "Logical assignment (`&&=`, `||=`, `??=`)",
    "category": "js",
    "tokens": [
      "\\?\\?=|\\|\\|=|&&="
    ],
    "weight": 3,
    "source": "curated",
    "fix": "Compile logical assignment operators for old engines (Babel logical-assignment-operators plugin) or expand into plain if-statements.",
    "support": {
      "android66": "no",
      "android96": "yes",
      "ios12": "no",
      "ios13": "no"
    }
  },
  {
    "id": "private-class-members",
    "label": "Private class members (`#field`)",
    "category": "js",
    "tokens": [
      "#[\\w]+\\s*(?:\\(|=)|\\.#\\w+"
    ],
    "weight": 2,
    "source": "curated",
    "fix": "Transpile private class members for legacy engines, or rename them to conventional `_`-prefixed fields.",
    "support": {
      "android66": "no",
      "android96": "yes",
      "ios12": "no",
      "ios13": "no"
    }
  },
  {
    "id": "promise-allsettled",
    "label": "Promise.allSettled / Promise.any",
    "category": "js",
    "tokens": [
      "Promise\\.(?:allSettled|any)\\b"
    ],
    "weight": 2,
    "source": "curated",
    "fix": "Add a small `Promise.allSettled` polyfill or switch to `Promise.all` with per-promise catch handlers.",
    "support": {
      "android66": "no",
      "android96": "yes",
      "ios12": "no",
      "ios13": "yes"
    }
  },
  {
    "id": "string-replaceall",
    "label": "String.prototype.replaceAll",
    "category": "js",
    "tokens": [
      "\\.replaceAll\\s*\\("
    ],
    "weight": 2,
    "source": "curated",
    "fix": "Use `split().join()` or a global regex replace for engines without String.prototype.replaceAll.",
    "support": {
      "android66": "no",
      "android96": "yes",
      "ios12": "no",
      "ios13": "yes"
    }
  },
  {
    "id": "array-at",
    "label": "Array.prototype.at (negative indexing)",
    "category": "js",
    "tokens": [
      "\\.at\\s*\\("
    ],
    "weight": 2,
    "source": "curated",
    "fix": "Replace `.at(-1)` with `arr[arr.length - 1]`, or add an Array.prototype.at polyfill.",
    "support": {
      "android66": "no",
      "android96": "no",
      "ios12": "no",
      "ios13": "no"
    }
  },
  {
    "id": "object-fromentries",
    "label": "Object.fromEntries",
    "category": "js",
    "tokens": [
      "Object\\.fromEntries\\b"
    ],
    "weight": 2,
    "source": "curated",
    "fix": "Add the tiny Object.fromEntries polyfill, or build the object with `reduce()`.",
    "support": {
      "android66": "no",
      "android96": "yes",
      "ios12": "no",
      "ios13": "no"
    }
  },
  {
    "id": "structured-clone",
    "label": "structuredClone()",
    "category": "js",
    "tokens": [
      "structuredClone\\s*\\("
    ],
    "weight": 2,
    "source": "curated",
    "fix": "Use a JSON round-trip or a deep-clone helper instead of structuredClone() on legacy engines.",
    "support": {
      "android66": "no",
      "android96": "no",
      "ios12": "no",
      "ios13": "no"
    }
  },
  {
    "id": "bigint",
    "label": "BigInt literals (`123n`)",
    "category": "js",
    "tokens": [
      "(?<![\\w.])\\d+n\\b"
    ],
    "weight": 2,
    "source": "caniuse",
    "fix": "Avoid BigInt on legacy engines, or gate the code path behind `typeof BigInt !== 'undefined'` with a fallback.",
    "support": {
      "android66": "no",
      "android96": "yes",
      "ios12": "no",
      "ios13": "no"
    }
  },
  {
    "id": "es6-module-dynamic-import",
    "label": "Dynamic `import()`",
    "category": "js",
    "tokens": [
      "\\bimport\\s*\\("
    ],
    "weight": 1,
    "source": "caniuse",
    "fix": "Ensure your bundler lowers `import()` for old targets or falls back to static imports.",
    "support": {
      "android66": "yes",
      "android96": "yes",
      "ios12": "yes",
      "ios13": "yes"
    }
  },
  {
    "id": "wasm",
    "label": "WebAssembly",
    "category": "js",
    "tokens": [
      "WebAssembly\\."
    ],
    "weight": 1,
    "source": "caniuse",
    "fix": "Provide a JavaScript fallback when `WebAssembly` is undefined.",
    "support": {
      "android66": "yes",
      "android96": "yes",
      "ios12": "yes",
      "ios13": "yes"
    }
  },
  {
    "id": "webgpu",
    "label": "WebGPU",
    "category": "js",
    "tokens": [
      "navigator\\.gpu\\b"
    ],
    "weight": 1,
    "source": "caniuse",
    "fix": "Gate WebGPU access behind feature detection with a WebGL/canvas 2D fallback.",
    "support": {
      "android66": "no",
      "android96": "no",
      "ios12": "no",
      "ios13": "no"
    }
  },
  {
    "id": "css-has",
    "label": "`:has()` selector",
    "category": "css",
    "tokens": [
      ":has\\s*\\("
    ],
    "weight": 3,
    "source": "caniuse",
    "fix": "Replace `:has()` selectors with a class toggled in JS, or add an `@supports not (selector(:has(*)))` fallback block.",
    "support": {
      "android66": "no",
      "android96": "no",
      "ios12": "no",
      "ios13": "no"
    }
  },
  {
    "id": "css-nesting",
    "label": "Native CSS nesting (`&`)",
    "category": "css",
    "tokens": [
      "&\\s*[.{,>+~:\\[]"
    ],
    "weight": 2,
    "source": "caniuse",
    "fix": "Compile nested CSS with a build step (PostCSS Nesting or your Tailwind pipeline) so selectors ship flat.",
    "support": {
      "android66": "no",
      "android96": "no",
      "ios12": "no",
      "ios13": "no"
    }
  },
  {
    "id": "css-container-queries",
    "label": "Container queries",
    "category": "css",
    "tokens": [
      "@container\\b",
      "container-type\\s*:"
    ],
    "weight": 3,
    "source": "caniuse",
    "fix": "Provide media-query fallbacks inside `@supports not (container-type: inline-size)` for the same breakpoints.",
    "support": {
      "android66": "no",
      "android96": "no",
      "ios12": "no",
      "ios13": "no"
    }
  },
  {
    "id": "css-subgrid",
    "label": "CSS subgrid",
    "category": "css",
    "tokens": [
      "grid-template-(?:columns|rows)\\s*:[^;}]*\\bsubgrid\\b"
    ],
    "weight": 2,
    "source": "caniuse",
    "fix": "Define explicit grid tracks instead of `subgrid`, or gate it behind `@supports`.",
    "support": {
      "android66": "no",
      "android96": "no",
      "ios12": "no",
      "ios13": "no"
    }
  },
  {
    "id": "css-color-function",
    "label": "Modern color spaces (oklch/oklab/lab/lch)",
    "category": "css",
    "tokens": [
      "\\b(?:oklch|oklab|lch|lab)\\s*\\("
    ],
    "weight": 2,
    "source": "caniuse",
    "fix": "Ship legacy `rgb()`/`hsl()` values first and override them inside `@supports (color: oklch(0% 0 0))`.",
    "support": {
      "android66": "no",
      "android96": "no",
      "ios12": "partial",
      "ios13": "partial"
    }
  },
  {
    "id": "css-cascade-layers",
    "label": "Cascade layers (`@layer`)",
    "category": "css",
    "tokens": [
      "@layer\\b"
    ],
    "weight": 2,
    "source": "caniuse",
    "fix": "Flatten `@layer` blocks in the build, or provide an unlayered fallback with the same cascade order.",
    "support": {
      "android66": "no",
      "android96": "no",
      "ios12": "no",
      "ios13": "no"
    }
  },
  {
    "id": "css-backdrop-filter",
    "label": "backdrop-filter",
    "category": "css",
    "tokens": [
      "backdrop-filter\\s*:"
    ],
    "weight": 1,
    "source": "caniuse",
    "fix": "Provide a solid or semi-opaque background fallback where backdrop-filter is unsupported.",
    "support": {
      "android66": "no",
      "android96": "yes",
      "ios12": "yes",
      "ios13": "yes"
    }
  },
  {
    "id": "css-math-functions",
    "label": "CSS math functions (clamp/min/max/round)",
    "category": "css",
    "tokens": [
      "\\b(?:round|mod|rem)\\s*\\(|\\b(?:clamp|min|max)\\s*\\("
    ],
    "weight": 1,
    "source": "caniuse",
    "fix": "Precompute clamp() values as custom properties with static fallbacks; round()/mod() need Chromium 108+.",
    "support": {
      "android66": "no",
      "android96": "yes",
      "ios12": "partial",
      "ios13": "yes"
    }
  },
  {
    "id": "css-text-wrap-balance",
    "label": "text-wrap: balance",
    "category": "css",
    "tokens": [
      "text-wrap\\s*:\\s*balance"
    ],
    "weight": 1,
    "source": "caniuse",
    "fix": "Treat `text-wrap: balance` as a progressive enhancement only; ensure headlines wrap acceptably without it.",
    "support": {
      "android66": "no",
      "android96": "no",
      "ios12": "no",
      "ios13": "no"
    }
  },
  {
    "id": "css-aspect-ratio",
    "label": "aspect-ratio",
    "category": "css",
    "tokens": [
      "aspect-ratio\\s*:"
    ],
    "weight": 1,
    "source": "curated",
    "fix": "Use the padding-top aspect pattern (or a fixed-height fallback) for engines without `aspect-ratio`.",
    "support": {
      "android66": "no",
      "android96": "yes",
      "ios12": "no",
      "ios13": "no"
    }
  }
];
